name: SDK Publish (Unstable)

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-24.04
    outputs:
      number: ${{ steps.version.outputs.number }}
    steps:
      - id: version
        run: echo "number=$(date +'%Y.%m.%d')-unstable.$(date +'%Y%m%d%H%M')" >> "$GITHUB_OUTPUT"

  publish:
    needs: version
    uses: ./.github/workflows/sdk-publish-reusable.yaml
    with:
      configuration: unstable
      version: ${{ needs.version.outputs.number }}
      target-branch: openapi-unstable
      commit-message: Update unstable OpenAPI client
      force-push: true
    secrets:
      NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}
