name: SDK Publish

on:
  release:
    types:
      - published

jobs:
  version:
    runs-on: ubuntu-24.04
    if: ${{ startsWith(github.ref, 'refs/tags/v') && github.repository == 'jellyfin/jellyfin-sdk-csharp' }}
    outputs:
      number: ${{ steps.version.outputs.number }}
    steps:
      - id: version
        run: echo "number=$(echo '${{ github.event.release.tag_name }}' | tr -d v)" >> "$GITHUB_OUTPUT"

  publish:
    needs: version
    uses: ./.github/workflows/sdk-publish-reusable.yaml
    with:
      configuration: stable
      version: ${{ needs.version.outputs.number }}
      target-branch: master
      commit-message: Update stable OpenAPI client
      force-push: false
    secrets:
      NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}
